//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphaneOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbKutuphaneEntities : DbContext
    {
        public DbKutuphaneEntities()
            : base("name=DbKutuphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblEmanetler> TblEmanetler { get; set; }
        public virtual DbSet<TblKitaplar> TblKitaplar { get; set; }
        public virtual DbSet<TblKitapTurleri> TblKitapTurleri { get; set; }
        public virtual DbSet<TblUyeler> TblUyeler { get; set; }
    
        public virtual ObjectResult<AdmınLog_Result> AdmınLog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdmınLog_Result>("AdmınLog");
        }
    
        public virtual ObjectResult<KitapEmanetler_Result> KitapEmanetler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KitapEmanetler_Result>("KitapEmanetler");
        }
    }
}
