//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmanetler
    {
        public int EmanetNo { get; set; }
        public Nullable<int> uyeID { get; set; }
        public Nullable<int> kitapId { get; set; }
        public Nullable<System.DateTime> EmanetVermeTarihi { get; set; }
        public Nullable<System.DateTime> EmanetAlmaTarihi { get; set; }
        public Nullable<System.DateTime> EmanetIslemTarihi { get; set; }
        public Nullable<bool> EmanetDurum { get; set; }
    
        public virtual TblKitaplar TblKitaplar { get; set; }
        public virtual TblUyeler TblUyeler { get; set; }
    }
}
