//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblKitaplar()
        {
            this.TblEmanetler = new HashSet<TblEmanetler>();
        }
    
        public int kitapID { get; set; }
        public string kitapAd { get; set; }
        public string kitapYazari { get; set; }
        public string kitapTuru { get; set; }
        public Nullable<System.DateTime> kitapBaskiYili { get; set; }
        public string kitapDili { get; set; }
        public string YayinEvi { get; set; }
        public string Aciklama { get; set; }
        public string kitapFoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmanetler> TblEmanetler { get; set; }
    }
}
