//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKitapTurleri
    {
        public int turID { get; set; }
        public string kitapTuru { get; set; }
    }
}
